### ISSUE TITLE
SQL Injection vulnerability

### ISSUE THREAD

**Issue by dseller** [MatthK/Selfoss-Webfront#1]
Hi,

I came across your project on the `selfhosted` subreddit, decided to look at your code. One thing that immediately struck my eye was a SQL injection vunerability in `article.php`, as linked here:

https://github.com/MatthK/Selfoss-Webfront/blob/a66df218b70f9d8bc91aa44904c2f76b91c264c4/website/article.php#L17

I haven't checked the rest of the files, but in my experience if you have one SQL injection vulnerability, then there's probably more.

You can use parameters instead of string concatenation to make it secure.

Kind regards,
Dennis

**Comment by MatthK** [comment]
Yes, I am aware of that. The thing was created with the idea of having it behind a firewall installed for personal use, so the risk there should be limited. I might adjust that and also correct the other 2 potential cases.

**Comment by MatthK** [comment]
I have updated the SQL statements to prepared ones. That should hopefully fix the vulnerability.
