### ISSUE TITLE
Not an issue, just a comment

### ISSUE THREAD

**Issue by pandruszkow** [MatthK/Selfoss-Webfront#4]
Hey,

I just wanted to say that I find the design to be stunning . It looks super professional, and wouldn't be out of place on the website of one of the major newspapers.

**Comment by MatthK** [comment]
Thanks, highly appreciated. I wish there was a bit more control over the content though, so pictures could be used to attract attention, etc. But yeah, there's always something that could be better.

**Comment by jcollas** [comment]
Also wanted to say the design is striking.  I spent some time refactoring the code to allow an arbitrary number of sections and to use https://miniflux.app/ as a source.  Once I get it working again with selfoss, I'd be happy to submit it as a patch.

**Comment by MatthK** [comment]
Sounds great. I'm looking forward to see that.
